/** @format */

const cardsData = [
	{
		id: 0,
		name: "Card 000",
		section: 0,
		front: "./assets/000.png",
		back: "./assets/000b.png",
		border: "./assets/000bdr.png",
		borderBack: "./assets/000b-bdr.png",
	},
	{
		id: 1,
		name: "Card 001",
		section: 1,
		front: "./assets/001.png",
		back: "./assets/001b.png",
		border: "./assets/001bdr.png",
		borderBack: "./assets/001b-bdr.png",
	},
	{
		id: 2,
		name: "Card 002",
		section: 1,
		front: "./assets/002.png",
		back: "./assets/002b.png",
		border: "./assets/002bdr.png",
		borderBack: "./assets/002b-bdr.png",
	},
	{
		id: 3,
		name: "Card 003",
		section: 1,
		front: "./assets/003.png",
		back: "./assets/003b.png",
		border: "./assets/003bdr.png",
		borderBack: "./assets/003b-bdr.png",
	},
{
    id: 6,
    name: "Card 006",
    section: 1,
    front: "./assets/006.png",
    back: "./assets/006b.png",
    border: "./assets/006bdr.png",
    borderBack: "./assets/006b-bdr.png",
  },
  {
    id: 11,
    name: "Card 011",
    section: 1,
    front: "./assets/011.png",
    back: "./assets/011b.png",
    border: "./assets/011bdr.png",
    borderBack: "./assets/011b-bdr.png",
  },
  {
    id: 13,
    name: "Card 013",
    section: 1,
    front: "./assets/013.png",
    back: "./assets/013b.png",
    border: "./assets/013bdr.png",
    borderBack: "./assets/013b-bdr.png",
  },
  {
    id: 4,
    name: "Card 004",
    section: 1,
    front: "./assets/004.png",
    back: "./assets/004b.png",
    border: "./assets/004bdr.png",
    borderBack: "./assets/004b-bdr.png",
  },
  {
    id: 15,
    name: "Card 015",
    section: 1,
    front: "./assets/015.png",
    back: "./assets/015b.png",
    border: "./assets/015bdr.png",
    borderBack: "./assets/015b-bdr.png",
  },
  {
    id: 17,
    name: "Card 017",
    section: 1,
    front: "./assets/017.png",
    back: "./assets/017b.png",
    border: "./assets/017bdr.png",
    borderBack: "./assets/017b-bdr.png",
  },
  {
    id: 20,
    name: "Card 020",
    section: 1,
    front: "./assets/020.png",
    back: "./assets/020b.png",
    border: "./assets/020bdr.png",
    borderBack: "./assets/020b-bdr.png",
  },
  {
    id: 21,
    name: "Card 021",
    section: 1,
    front: "./assets/021.png",
    back: "./assets/021b.png",
    border: "./assets/021bdr.png",
    borderBack: "./assets/021b-bdr.png",
  },
  {
    id: 23,
    name: "Card 023",
    section: 1,
    front: "./assets/023.png",
    back: "./assets/023b.png",
    border: "./assets/023bdr.png",
    borderBack: "./assets/023b-bdr.png",
  },
{
    id: 24,
    name: "Card 024",
    section: 1,
    front: "./assets/024.png",
    back: "./assets/024b.png",
    border: "./assets/024bdr.png",
    borderBack: "./assets/024b-bdr.png",
  },
  {
    id: 25,
    name: "Card 025",
    section: 1,
    front: "./assets/025.png",
    back: "./assets/025b.png",
    border: "./assets/025bdr.png",
    borderBack: "./assets/025b-bdr.png",
  },
  {
    id: 26,
    name: "Card 026",
    section: 1,
    front: "./assets/026.png",
    back: "./assets/026b.png",
    border: "./assets/026bdr.png",
    borderBack: "./assets/026b-bdr.png",
  },
  {
    id: 27,
    name: "Card 027",
    section: 2,
    front: "./assets/027.png",
    back: "./assets/027b.png",
    border: "./assets/027bdr.png",
    borderBack: "./assets/027b-bdr.png",
  },
  {
    id: 28,
    name: "Card 028",
    section: 2,
    front: "./assets/028.png",
    back: "./assets/028b.png",
    border: "./assets/028bdr.png",
    borderBack: "./assets/028b-bdr.png",
  },
  {
    id: 30,
    name: "Card 030",
    section: 2,
    front: "./assets/030.png",
    back: "./assets/030b.png",
    border: "./assets/030bdr.png",
    borderBack: "./assets/030b-bdr.png",
  },
  {
    id: 32,
    name: "Card 032",
    section: 2,
    front: "./assets/032.png",
    back: "./assets/032b.png",
    border: "./assets/032bdr.png",
    borderBack: "./assets/032b-bdr.png",
  },
  {
    id: 33,
    name: "Card 033",
    section: 2,
    front: "./assets/033.png",
    back: "./assets/033b.png",
    border: "./assets/033bdr.png",
    borderBack: "./assets/033b-bdr.png",
  },
  {
    id: 35,
    name: "Card 035",
    section: 2,
    front: "./assets/035.png",
    back: "./assets/035b.png",
    border: "./assets/035bdr.png",
    borderBack: "./assets/035b-bdr.png",
  },

];

export default cardsData;