/** @format */

const cardsData = [
  // ============================================================
  // SECTION 0 — UNNAMED
  // ============================================================

  {
    id: 0,
    name: "Card 000",
    section: 0,
    front: "./assets/000.jpg",
    back: "./assets/000b.jpg",
    border: "./assets/000bdr.png",
    borderBack: "./assets/000b-bdr.png",
  },

  // ============================================================
  // SECTION 1 — ADVENTURERS
  // ============================================================

  {
    id: 1,
    name: "Card 001",
    section: 1,
    front: "./assets/001.jpg",
    back: "./assets/001b.jpg",
    border: "./assets/001bdr.png",
    borderBack: "./assets/001b-bdr.png",
  },
  {
    id: 2,
    name: "Card 002",
    section: 1,
    front: "./assets/002.jpg",
    back: "./assets/002b.jpg",
    border: "./assets/002bdr.png",
    borderBack: "./assets/002b-bdr.png",
  },
  {
    id: 3,
    name: "Card 003",
    section: 1,
    front: "./assets/003.jpg",
    back: "./assets/003b.jpg",
    border: "./assets/003bdr.png",
    borderBack: "./assets/003b-bdr.png",
  },
  {
    id: 4,
    name: "Card 004",
    section: 1,
    front: "./assets/004.jpg",
    back: "./assets/004b.jpg",
    border: "./assets/004bdr.png",
    borderBack: "./assets/004b-bdr.png",
  },
  {
    id: 5,
    name: "Card 005",
    section: 1,
    front: "./assets/005.jpg",
    back: "./assets/005b.jpg",
    border: "./assets/005bdr.png",
    borderBack: "./assets/005b-bdr.png",
  },
  {
    id: 6,
    name: "Card 006",
    section: 1,
    front: "./assets/006.jpg",
    back: "./assets/006b.jpg",
    border: "./assets/006bdr.png",
    borderBack: "./assets/006b-bdr.png",
  },
  {
    id: 7,
    name: "Card 007",
    section: 1,
    front: "./assets/007.jpg",
    back: "./assets/007b.jpg",
    border: "./assets/007bdr.png",
    borderBack: "./assets/007b-bdr.png",
  },
  {
    id: 8,
    name: "Card 008",
    section: 1,
    front: "./assets/008.jpg",
    back: "./assets/008b.jpg",
    border: "./assets/008bdr.png",
    borderBack: "./assets/008b-bdr.png",
  },
  {
    id: 9,
    name: "Card 009",
    section: 1,
    front: "./assets/009.jpg",
    back: "./assets/009b.jpg",
    border: "./assets/009bdr.png",
    borderBack: "./assets/009b-bdr.png",
  },
  {
    id: 10,
    name: "Card 010",
    section: 1,
    front: "./assets/010.jpg",
    back: "./assets/010b.jpg",
    border: "./assets/010bdr.png",
    borderBack: "./assets/010b-bdr.png",
  },
  {
    id: 11,
    name: "Card 011",
    section: 1,
    front: "./assets/011.jpg",
    back: "./assets/011b.jpg",
    border: "./assets/011bdr.png",
    borderBack: "./assets/011b-bdr.png",
  },
  {
    id: 12,
    name: "Card 012",
    section: 1,
    front: "./assets/012.jpg",
    back: "./assets/012b.jpg",
    border: "./assets/012bdr.png",
    borderBack: "./assets/012b-bdr.png",
  },
  {
    id: 13,
    name: "Card 013",
    section: 1,
    front: "./assets/013.jpg",
    back: "./assets/013b.jpg",
    border: "./assets/013bdr.png",
    borderBack: "./assets/013b-bdr.png",
  },
  {
    id: 14,
    name: "Card 014",
    section: 1,
    front: "./assets/014.jpg",
    back: "./assets/014b.jpg",
    border: "./assets/014bdr.png",
    borderBack: "./assets/014b-bdr.png",
  },
  {
    id: 15,
    name: "Card 015",
    section: 1,
    front: "./assets/015.jpg",
    back: "./assets/015b.jpg",
    border: "./assets/015bdr.png",
    borderBack: "./assets/015b-bdr.png",
  },
  {
    id: 16,
    name: "Card 016",
    section: 1,
    front: "./assets/016.jpg",
    back: "./assets/016b.jpg",
    border: "./assets/016bdr.png",
    borderBack: "./assets/016b-bdr.png",
  },
  {
    id: 17,
    name: "Card 017",
    section: 1,
    front: "./assets/017.jpg",
    back: "./assets/017b.jpg",
    border: "./assets/017bdr.png",
    borderBack: "./assets/017b-bdr.png",
  },
  {
    id: 18,
    name: "Card 018",
    section: 1,
    front: "./assets/018.jpg",
    back: "./assets/018b.jpg",
    border: "./assets/018bdr.png",
    borderBack: "./assets/018b-bdr.png",
  },
  {
    id: 19,
    name: "Card 019",
    section: 1,
    front: "./assets/019.jpg",
    back: "./assets/019b.jpg",
    border: "./assets/019bdr.png",
    borderBack: "./assets/019b-bdr.png",
  },
  {
    id: 20,
    name: "Card 020",
    section: 1,
    front: "./assets/020.jpg",
    back: "./assets/020b.jpg",
    border: "./assets/020bdr.png",
    borderBack: "./assets/020b-bdr.png",
  },
  {
    id: 21,
    name: "Card 021",
    section: 1,
    front: "./assets/021.jpg",
    back: "./assets/021b.jpg",
    border: "./assets/021bdr.png",
    borderBack: "./assets/021b-bdr.png",
  },
  {
    id: 22,
    name: "Card 022",
    section: 1,
    front: "./assets/022.jpg",
    back: "./assets/022b.jpg",
    border: "./assets/022bdr.png",
    borderBack: "./assets/022b-bdr.png",
  },
  {
    id: 23,
    name: "Card 023",
    section: 1,
    front: "./assets/023.jpg",
    back: "./assets/023b.jpg",
    border: "./assets/023bdr.png",
    borderBack: "./assets/023b-bdr.png",
  },
  {
    id: 24,
    name: "Card 024",
    section: 1,
    front: "./assets/024.jpg",
    back: "./assets/024b.jpg",
    border: "./assets/024bdr.png",
    borderBack: "./assets/024b-bdr.png",
  },
  {
    id: 25,
    name: "Card 025",
    section: 1,
    front: "./assets/025.jpg",
    back: "./assets/025b.jpg",
    border: "./assets/025bdr.png",
    borderBack: "./assets/025b-bdr.png",
  },
  {
    id: 26,
    name: "Card 026",
    section: 1,
    front: "./assets/026.jpg",
    back: "./assets/026b.jpg",
    border: "./assets/026bdr.png",
    borderBack: "./assets/026b-bdr.png",
  },
  {
    id: 27,
    name: "Card 027",
    section: 1,
    front: "./assets/027.jpg",
    back: "./assets/027b.jpg",
    border: "./assets/027bdr.png",
    borderBack: "./assets/027b-bdr.png",
  },
  {
    id: 28,
    name: "Card 028",
    section: 1,
    front: "./assets/028.jpg",
    back: "./assets/028b.jpg",
    border: "./assets/028bdr.png",
    borderBack: "./assets/028b-bdr.png",
  },
  {
    id: 29,
    name: "Card 029",
    section: 1,
    front: "./assets/029.jpg",
    back: "./assets/029b.jpg",
    border: "./assets/029bdr.png",
    borderBack: "./assets/029b-bdr.png",
  },
  {
    id: 30,
    name: "Card 030",
    section: 1,
    front: "./assets/030.jpg",
    back: "./assets/030b.jpg",
    border: "./assets/030bdr.png",
    borderBack: "./assets/030b-bdr.png",
  },

  // ============================================================
  // SECTION 2 — LEGENDS
  // ============================================================

  {
    id: 31,
    name: "Card 031",
    section: 2,
    front: "./assets/031.jpg",
    back: "./assets/031b.jpg",
    border: "./assets/031bdr.png",
    borderBack: "./assets/031b-bdr.png",
  },
  {
    id: 32,
    name: "Card 032",
    section: 2,
    front: "./assets/032.jpg",
    back: "./assets/032b.jpg",
    border: "./assets/032bdr.png",
    borderBack: "./assets/032b-bdr.png",
  },
  {
    id: 33,
    name: "Card 033",
    section: 2,
    front: "./assets/033.jpg",
    back: "./assets/033b.jpg",
    border: "./assets/033bdr.png",
    borderBack: "./assets/033b-bdr.png",
  },
  {
    id: 34,
    name: "Card 034",
    section: 2,
    front: "./assets/034.jpg",
    back: "./assets/034b.jpg",
    border: "./assets/034bdr.png",
    borderBack: "./assets/034b-bdr.png",
  },
  {
    id: 35,
    name: "Card 035",
    section: 2,
    front: "./assets/035.jpg",
    back: "./assets/035b.jpg",
    border: "./assets/035bdr.png",
    borderBack: "./assets/035b-bdr.png",
  },
  {
    id: 36,
    name: "Card 036",
    section: 2,
    front: "./assets/036.jpg",
    back: "./assets/036b.jpg",
    border: "./assets/036bdr.png",
    borderBack: "./assets/036b-bdr.png",
  },
  {
    id: 37,
    name: "Card 037",
    section: 2,
    front: "./assets/037.jpg",
    back: "./assets/037b.jpg",
    border: "./assets/037bdr.png",
    borderBack: "./assets/037b-bdr.png",
  },
  {
    id: 38,
    name: "Card 038",
    section: 2,
    front: "./assets/038.jpg",
    back: "./assets/038b.jpg",
    border: "./assets/038bdr.png",
    borderBack: "./assets/038b-bdr.png",
  },
  {
    id: 39,
    name: "Card 039",
    section: 2,
    front: "./assets/039.jpg",
    back: "./assets/039b.jpg",
    border: "./assets/039bdr.png",
    borderBack: "./assets/039b-bdr.png",
  },
  {
    id: 40,
    name: "Card 040",
    section: 2,
    front: "./assets/040.jpg",
    back: "./assets/040b.jpg",
    border: "./assets/040bdr.png",
    borderBack: "./assets/040b-bdr.png",
  },
  {
    id: 41,
    name: "Card 041",
    section: 2,
    front: "./assets/041.jpg",
    back: "./assets/041b.jpg",
    border: "./assets/041bdr.png",
    borderBack: "./assets/041b-bdr.png",
  },
  {
    id: 42,
    name: "Card 042",
    section: 2,
    front: "./assets/042.jpg",
    back: "./assets/042b.jpg",
    border: "./assets/042bdr.png",
    borderBack: "./assets/042b-bdr.png",
  },
  {
    id: 43,
    name: "Card 043",
    section: 2,
    front: "./assets/043.jpg",
    back: "./assets/043b.jpg",
    border: "./assets/043bdr.png",
    borderBack: "./assets/043b-bdr.png",
  },
  {
    id: 44,
    name: "Card 044",
    section: 2,
    front: "./assets/044.jpg",
    back: "./assets/044b.jpg",
    border: "./assets/044bdr.png",
    borderBack: "./assets/044b-bdr.png",
  },
  {
    id: 45,
    name: "Card 045",
    section: 2,
    front: "./assets/045.jpg",
    back: "./assets/045b.jpg",
    border: "./assets/045bdr.png",
    borderBack: "./assets/045b-bdr.png",
  },

  // ============================================================
  // SECTION 3 — COMPANIONS
  // ============================================================

  {
    id: 46,
    name: "Card 046",
    section: 3,
    front: "./assets/046.jpg",
    back: "./assets/046b.jpg",
    border: "./assets/046bdr.png",
    borderBack: "./assets/046b-bdr.png",
  },
  {
    id: 47,
    name: "Card 047",
    section: 3,
    front: "./assets/047.jpg",
    back: "./assets/047b.jpg",
    border: "./assets/047bdr.png",
    borderBack: "./assets/047b-bdr.png",
  },
  {
    id: 48,
    name: "Card 048",
    section: 3,
    front: "./assets/048.jpg",
    back: "./assets/048b.jpg",
    border: "./assets/048bdr.png",
    borderBack: "./assets/048b-bdr.png",
  },
  {
    id: 49,
    name: "Card 049",
    section: 3,
    front: "./assets/049.jpg",
    back: "./assets/049b.jpg",
    border: "./assets/049bdr.png",
    borderBack: "./assets/049b-bdr.png",
  },
  {
    id: 50,
    name: "Card 050",
    section: 3,
    front: "./assets/050.jpg",
    back: "./assets/050b.jpg",
    border: "./assets/050bdr.png",
    borderBack: "./assets/050b-bdr.png",
  },
  {
    id: 51,
    name: "Card 051",
    section: 3,
    front: "./assets/051.jpg",
    back: "./assets/051b.jpg",
    border: "./assets/051bdr.png",
    borderBack: "./assets/051b-bdr.png",
  },
  {
    id: 52,
    name: "Card 052",
    section: 3,
    front: "./assets/052.jpg",
    back: "./assets/052b.jpg",
    border: "./assets/052bdr.png",
    borderBack: "./assets/052b-bdr.png",
  },
  {
    id: 53,
    name: "Card 053",
    section: 3,
    front: "./assets/053.jpg",
    back: "./assets/053b.jpg",
    border: "./assets/053bdr.png",
    borderBack: "./assets/053b-bdr.png",
  },
  {
    id: 54,
    name: "Card 054",
    section: 3,
    front: "./assets/054.jpg",
    back: "./assets/054b.jpg",
    border: "./assets/054bdr.png",
    borderBack: "./assets/054b-bdr.png",
  },

  // ============================================================
  // SECTION 4 — PATRONS
  // ============================================================

  {
    id: 55,
    name: "Card 055",
    section: 4,
    front: "./assets/055.jpg",
    back: "./assets/055b.jpg",
    border: "./assets/055bdr.png",
    borderBack: "./assets/055b-bdr.png",
  },
  {
    id: 56,
    name: "Card 056",
    section: 4,
    front: "./assets/056.jpg",
    back: "./assets/056b.jpg",
    border: "./assets/056bdr.png",
    borderBack: "./assets/056b-bdr.png",
  },
  {
    id: 57,
    name: "Card 057",
    section: 4,
    front: "./assets/057.jpg",
    back: "./assets/057b.jpg",
    border: "./assets/057bdr.png",
    borderBack: "./assets/057b-bdr.png",
  },
  {
    id: 58,
    name: "Card 058",
    section: 5,
    front: "./assets/058.jpg",
    back: "./assets/058b.jpg",
    border: "./assets/058bdr.png",
    borderBack: "./assets/058b-bdr.png",
  },

];

export default cardsData;